// Package docgen generates documentation artifacts from plans/missions (AESP-0008 / DOC-GEN).
package docgen

import (
	"fmt"
	"strings"
	"sync"
	"time"

	"github.com/kishoreHQ/Hermes-Agent-OS/kernel/pkg/types"
)

// Document is a generated doc unit.
type Document struct {
	ID        string              `json:"id"`
	Title     string              `json:"title"`
	Kind      string              `json:"kind"` // readme|runbook|api
	Body      string              `json:"body"`
	MissionID types.MissionID     `json:"missionId,omitempty"`
	Digest    types.ArtifactDigest `json:"digest,omitempty"`
	CreatedAt time.Time           `json:"createdAt"`
}

// Generator produces docs and keeps a catalog.
type Generator struct {
	mu   sync.Mutex
	docs map[string]*Document
	seq  int
}

func New() *Generator {
	return &Generator{docs: map[string]*Document{}}
}

type GenerateReq struct {
	Title     string `json:"title"`
	Kind      string `json:"kind"`
	Goal      string `json:"goal"`
	MissionID string `json:"missionId"`
	PlanID    string `json:"planId"`
}

func (g *Generator) Generate(req GenerateReq) (*Document, error) {
	if req.Title == "" {
		req.Title = "Generated documentation"
	}
	if req.Kind == "" {
		req.Kind = "readme"
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", req.Title)
	fmt.Fprintf(&b, "Generated by Hermes docgen at %s.\n\n", time.Now().UTC().Format(time.RFC3339))
	if req.Goal != "" {
		fmt.Fprintf(&b, "## Goal\n\n%s\n\n", req.Goal)
	}
	if req.MissionID != "" {
		fmt.Fprintf(&b, "## Mission\n\n`%s`\n\n", req.MissionID)
	}
	if req.PlanID != "" {
		fmt.Fprintf(&b, "## Plan\n\n`%s`\n\n", req.PlanID)
	}
	fmt.Fprintf(&b, "## Notes\n\n- Vendor-neutral\n- Host API documented separately in OpenAPI\n")

	body := b.String()
	g.mu.Lock()
	defer g.mu.Unlock()
	g.seq++
	d := &Document{
		ID: fmt.Sprintf("doc_%d", g.seq), Title: req.Title, Kind: req.Kind, Body: body,
		MissionID: types.MissionID(req.MissionID), CreatedAt: time.Now().UTC(),
	}
	g.docs[d.ID] = d
	cp := *d
	return &cp, nil
}

func (g *Generator) List() []Document {
	g.mu.Lock()
	defer g.mu.Unlock()
	out := make([]Document, 0, len(g.docs))
	for _, d := range g.docs {
		out = append(out, *d)
	}
	return out
}

func (g *Generator) Get(id string) (Document, bool) {
	g.mu.Lock()
	defer g.mu.Unlock()
	d, ok := g.docs[id]
	if !ok {
		return Document{}, false
	}
	return *d, true
}
